// <auto-generated />
using AIONYS_TestTask.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AIONYS_TestTask.Migrations
{
    [DbContext(typeof(SqliteDataContext))]
    [Migration("20201202170411_SQliteMigration")]
    partial class SQliteMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AIONYS_TestTask.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Today I`m running!"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Today I`m reading"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
